import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :bitblocks, BitblocksWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  url: [port: 443, scheme: "https", host: "www.bitblocks.app"],
  force_ssl: [rewrite_on: [:x_forwarded_proto], exclude: [paths: ["/healthz"]]]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Bitblocks.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Transaction fetching runs on two dedicated concurrency-1 lanes so the chain
# tip is never starved by historical backfill: one current + one past block
# fetch at a time, in parallel. Tuned conservatively for t3.medium (4GB RAM).
config :bitblocks, Oban,
  queues: [default: 10, transactions_tip: 1, transactions_backfill: 1, blocks: 1]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
